### ISSUE TITLE
qubesadmin.exc.StoragePoolException:   Snapshot origin LV vm-sd-small-bookworm-template-root not found in Volume group qubes_dom0

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-workstation-ci#54]
See in https://ws-ci-runner.securedrop.org/2024-04-15-143208874374-c2c7196fbc810600175a195716277e611b4b8076-Qubes_4.2_B-update_20240415045017.log.txt

```
INFO:[2024-04-15-15:27:37:988183] ERROR: test_gpg_domain_configured (test_app.SD_App_Tests.test_gpg_domain_configured)
INFO:[2024-04-15-15:27:37:988213] ----------------------------------------------------------------------
INFO:[2024-04-15-15:27:37:988240] Traceback (most recent call last):
INFO:[2024-04-15-15:27:37:988271]   File "/home/user/securedrop-workstation/tests/test_app.py", line 10, in setUp
INFO:[2024-04-15-15:27:37:988301]     super(SD_App_Tests, self).setUp()
INFO:[2024-04-15-15:27:37:988331]   File "/home/user/securedrop-workstation/tests/base.py", line 52, in setUp
INFO:[2024-04-15-15:27:37:988359]     self.vm.start()
INFO:[2024-04-15-15:27:37:988389]   File "/usr/lib/python3.11/site-packages/qubesadmin/vm/__init__.py", line 103, in start
INFO:[2024-04-15-15:27:37:988418]     self.qubesd_call(self._method_dest, 'admin.vm.Start')
INFO:[2024-04-15-15:27:37:988451]   File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 76, in qubesd_call
INFO:[2024-04-15-15:27:37:988482]     return self.app.qubesd_call(dest, method, arg, payload,
INFO:[2024-04-15-15:27:37:988513]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO:[2024-04-15-15:27:37:988541]   File "/usr/lib/python3.11/site-packages/qubesadmin/app.py", line 770, in qubesd_call
INFO:[2024-04-15-15:27:37:988571]     return self._parse_qubesd_response(return_data)
INFO:[2024-04-15-15:27:37:988614]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO:[2024-04-15-15:27:37:988644]   File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 111, in _parse_qubesd_response
INFO:[2024-04-15-15:27:37:988675]     raise exc_class(format_string, *args)
INFO:[2024-04-15-15:27:37:988703] qubesadmin.exc.StoragePoolException:   Snapshot origin LV vm-sd-small-bookworm-template-root not found in Volume group qubes_dom0.
```

Not sure if it's just a fluke or what, but filing in case we see it again and it merits further investigation...

**Comment by nathandyer** [comment]
Not reproduced again; closing
